### ISSUE TITLE
Using existing blockchain to bootstrap a new installation does not work

### ISSUE THREAD

**Issue by gdiscord** [project-liberty/wallet#32] opened 2018-12-14 13:33 UTC
This issue tracker is only for technical issues related to Liberty Core.
General Liberty questions and/or support requests and are best directed to the [Liberty Discord](https://discord.liberty-coin.com).

### Describe the issue
When using existing chain to bootstrap a new installation the new installation does not advance past the block at which point the old snapshot was taken. It gets stuck there forever.
### Can you reliably reproduce the issue? 
Yes
#### If so, please list the steps to reproduce below:
1. Make a copy of blocks, chainstate and peers.dat for an existing wallet that is fully synced to the tip of the chain (take note of the block height before the copy).
2. start a new wallet instance using the files copied from step 1.
3. issue cli command such as getinfo or getblockcount.

### Expected behavior
The blocks should advance and get fully synced to the chain

### Actual behavior
blocks get stuck at the height the snapshot/copy of the chain was made.
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Liberty Core are you using?
v5.0.58

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by binarysculptor** [comment] 2019-01-25 01:36
Unable to reproduce the issue using Windows x64 build of `5.1.1`. Closing unless there is additional info provided.

**Closed as completed by binarysculptor** 2019-01-25 01:36 UTC
Labels: bug
